# -*- coding: utf-8 -*-
"""trip_data_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qCVTKIpbTsDwpD343ABWUFVlFguIZ5VO
"""

from google.colab import files
uploaded = files.upload()

from pyspark.sql import SparkSession
spark = SparkSession.builder.appName("csv_upload").getOrCreate()

df = spark.read.csv('yellow_tripdata_example.csv', header=True, inferSchema=True)
df.show()

!pip install pyspark

from pyspark.sql import SparkSession
from pyspark.sql.functions import col, to_timestamp, unix_timestamp, round

# Initialize Spark session
spark = SparkSession.builder.appName("RideSharingETL").getOrCreate()

# Load dataset (paste the copied path below)
file_path = "/content/yellow_tripdata_example.csv"  # Update path if needed
df = spark.read.option("header", True).csv(file_path)

# Convert datetime columns
df = df.withColumn("pickup_datetime", to_timestamp(col("tpep_pickup_datetime")))
df = df.withColumn("dropoff_datetime", to_timestamp(col("tpep_dropoff_datetime")))

# Calculate trip duration (in minutes)
df = df.withColumn("trip_duration", round((unix_timestamp(col("dropoff_datetime")) - unix_timestamp(col("pickup_datetime"))) / 60, 2))

# Remove trips with 0 or negative distance
df = df.filter(col("trip_distance") > 0)

# Show transformed data
df.select("pickup_datetime", "dropoff_datetime", "trip_distance", "trip_duration").show()

# Save the cleaned data as a Parquet file (in Colab storage)
df.write.mode("overwrite").parquet("/content/cleaned_taxi_data")

from google.colab import files
files.download("trip_data_analysis.ipynb")

